name: Compile Latex and Release PDF  

on:
  push:
    tags:
      - 'v*.*.*'
#     branches:
#       - main
  workflow_dispatch:

permissions: write-all
#   contents: write
#   pages: write
#   id-token: write
#   actions: write
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Compile latex document
        uses: docker://ghcr.io/pzktit/texlivedev:latest
        with:
          entrypoint: /bin/bash
          args: |
            -c "whoami && pwd && ls -l . && date && sudo latexmk -lualatex"

      - name: Populate output file
        run: mkdir --parent ./public && cp *.pdf ./public/ && cp -rf ./docs/* ./public/
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './public/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1    
